### ISSUE TITLE
The config statusbadge.enabled expects a boolean instead of a string

### ISSUE THREAD

**Issue by Angelin01** [argoproj/argo-helm#2869]
### Describe the bug

In the current helm chart version, [the `argo-cd.config.cm.presets` function](https://github.com/argoproj/argo-helm/blob/argo-cd-7.3.11/charts/argo-cd/templates/_helpers.tpl#L183-L193) expects `statusbadge.enabled` to be a boolean, instead of a string, which gives this error in templates:

```
Error: template: argo-cd/templates/dex/deployment.yaml:30:24: executing "argo-cd/templates/dex/deployment.yaml" at <include (print $.Template.BasePath "/argocd-configs/argocd-cm.yaml") .>: error calling include: template: argo-cd/templates/argocd-configs/argocd-cm.yaml:16:6: executing "argo-cd/templates/argocd-configs/argocd-cm.yaml" at <include "argo-cd.config.cm" .>: error calling include: template: argo-cd/templates/_helpers.tpl:200:15: executing "argo-cd.config.cm" at <include "argo-cd.config.cm.presets" .>: error calling include: template: argo-cd/templates/_helpers.tpl:186:56: executing "argo-cd.config.cm.presets" at <eq true>: error calling eq: incompatible types for comparison
```

Other issues have already pointed this out, that swapping the value to a boolean "fixes it": https://github.com/argoproj/argo-helm/issues/2663

However, I'd argue that the current behavior is a bug, given that [in ArgoCD's own documentation, `stautsbadge.enabled` is a string](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/), much like every other "boolean" value. This behavior is confusing for folks configuring the application.

Edit: to add further context, this used to work in 5.51:
```yaml
configs:
  cm:
    statusbadge.enabled: "true"
```

### Related helm chart

argo-cd

### Helm chart version

All versions after da0068075833e9a58d129f3963fb915819d8a062

### To Reproduce

1. Grab an affected chart version
2. Set `.configs.cm."statusbadge.enabled"` to a string like `"true"`
3. Run helm template

### Expected behavior

Helm template works successfully with `statusbadge.enabled` as a string, matching ArgoCD's documentation

**Comment by Angelin01** [comment]
In response to: https://github.com/argoproj/argo-helm/pull/2870#issuecomment-2278053800

I understand the result is OK, that is not the argument here. The result is OK because we cast all values to strings here: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/_helpers.tpl#L202

However, at the VALUES, [all values were converted to bools](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L165-L226) (which was an undocumented breaking change):

```yaml
configs:
  cm:
    server.rbac.log.enforce.enable: false
    exec.enabled: false
    admin.enabled: true
    statusbadge.enabled: false
```

What I am arguing is that this is **_unexpected_**. When I look at these values, I think they will map DIRECTLY to ArgoCD's CM: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/

It "looks like it does", and it in fact, it does, but we cast all values to strings. So, suddenly requiring the user to fill out a bool instead of a string is "unexpected". This caused breakage when updating (in my use case) and also the one reported in #2663.
